version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u151
    steps:
      - checkout
      - run:
          name: Build archive
          command: ./gradlew build
      - run:
          name: Upload to bintray
          command: ./gradlew bintrayUpload